---

#############################################
# Tエレメント動作確認デバッグ用設定ファイル #
#############################################

template: ./template/debug/template_50ohm.sp

# pop_size: 100
# generation: 2000
# brother_num: 8

seeds:
- 1
- 2
- 3

optpts:
- optpt1

weight:
  optpt1: 1.0

score_normalize: false

versus:
  optpt1: vspt1

score_calc_methods:
- - optpt1
  - integral
