---

############################################
## ML505 Bit Error Late 系用設定ファイル ###
############################################

### 注意事項 ###
# * 安達（2013年度修士卒）から引き継ぎ，関（2014年度修士卒）が ver 2.3 用に修正したものです．
# * 安達さんは評価関数として誤差面積を2乗する関数を用いていましたが（修論など参照），ver 2.3 ではこれを廃止しているため，評価関数として通常の誤差面積を利用しています．

template: ./template/ML505/template_BER.sp

### 母集合の個体数 ###
# pop_size: 100

### 遺伝的アルゴリズムの繰り返し世代数 ###
# generation: 2000

### 一回の交叉で生成する子供の数（兄弟の数） ###
# brother_num: 10

### 交叉メソッド ###
crossover:
  length: dependent_sum_blx_obsolete
  impedance: n_point_crossover

### セグメントの特性インピーダンスの最小値 ###
minimum_impedance: 30

### セグメントの特性インピーダンスの最大値 ###
maximum_impedance: 120

### セグメントの特性インピーダンスの間隔 ###
impedance_step: 5

### 乱数シード ###
seeds:
- 1

### 最適化する観測点 ###
optpts:
- optpt1

### 観測点毎の重み ###
weight:
  optpt1: 1.0

### 観測波形に対応する理想波形の観測点 ###
versus:
  optpt1: vspt1

### スコア計算関数 ###
score_calc_methods:
- - optpt1
  - integral

### 古いアルゴリズム利用モード ###
use_obsolete: true
