---

##################################################
# 分岐配線用，孤立波の複合評価関数の設定ファイル #
##################################################

### 注意事項 ###
# * 栗原（2013年度修士卒）から引き継ぎ，関（2014年度修士卒）が ver 2.3 用に修正したものです．
# * template_branch.sp は主配線・分岐配線を全てSTL化します．

template: ./template/branch/template_branch.sp

### 母集合の個体数 ###
# pop_size: 100

### 遺伝的アルゴリズムの繰り返し世代数 ###
# generation: 3000

### 一回の交叉で生成する子供の数（兄弟の数） ###
# brother_num: 10

### 交叉メソッド ###
crossover:
  length: dependent_sum_blx_obsolete
  impedance: n_point_crossover

### セグメントの特性インピーダンスの最小値 ###
minimum_impedance: 30

### セグメントの特性インピーダンスの最大値 ###
maximum_impedance: 120

### セグメントの特性インピーダンスの間隔 ###
impedance_step: 5

### 乱数シード ###
seeds:
- 1

### 最適化する観測点 ###
optpts:
- optpt1

### 観測点毎の重み ###
weight:
  optpt1: 1.0

### 観測波形に対応する理想波形の観測点 ###
versus:
  optpt1: vspt1

### スコア計算関数 ###
score_calc_methods:
-
  - optpt1
  - multi
  -
    -
      - 19n
      - integral
      - 1.0
    -
      - 22.5n
      - maxvoltage
      - 1.0

### 古いアルゴリズム利用モード ###
use_obsolete: true
