---

#######################################################################
###  10Gbps孤立波設計クロストーク系（2サブスペース）の設定ファイル  ###
#######################################################################

### STL設計に用いるテンプレートファイルのパス ###
template: ./template/crosstalk/template_alone_2sub.sp

### 母集合の個体数 ###
# pop_size: 100

### 遺伝的アルゴリズムの繰り返し世代数 ###
# generation: 2000

### 一回の交叉で生成する子供の数（兄弟の数） ###
# brother_num: 8

### 乱数シード ###
seeds:
- 11

### セグメントの特性インピーダンスの最小値 ###
minimum_impedance: 40

### セグメントの特性インピーダンスの最大値 ###
maximum_impedance: 120

### セグメントの特性インピーダンスの間隔 ###
impedance_step: 5

### セグメント長の最小値 ###
minimum_length: 1m

### セグメント長の間隔 ###
length_step: 0.5m

### 最適化する観測点 ###
optpts:
- optpt1
- optpt2

### 観測点毎の重み ###
weight:
  optpt1: 1.0
  optpt2: 1.0

### 観測波形に対応する理想波形の観測点 ###
versus:                 
  optpt1: vspt1
  optpt2: vspt2


### スコア計算関数 ###
score_calc_methods:
-
  - optpt1
  - multi
  -
    -
      - 0.6n
      - integral
      - 1.0
    -
      - 0.85n
      - maxvoltage
      - 1.5
-
  - optpt2
  - maxvoltage
