---

#######################################################################
###  250MHzクロック設計クロストーク系（無損失伝送線）の設定ファイル ###
#######################################################################

### 備考 ###
# 関（2014年度卒）が卒論及びEDAPS2012で用いた250MHzクロック-400mm伝送線の設定ファイル
# 関(2014年度卒)が卒業研究で使ったのは STLデザイナー1 でしたが，卒論及び残っていたファイルを参考にSTLデザイナー2用を作成しました．
# ADS 等では設計結果に 2503 の数値がついている結果が STLデザイナー1 でこの設定で設計した結果です．

### STL設計に用いるテンプレートファイルのパス ###
template: ./template/crosstalk/template_250MHz.sp

### 母集合の個体数 ###
# pop_size: 100

### 遺伝的アルゴリズムの繰り返し世代数 ###
# generation: 8000

### 一回の交叉で生成する子供の数（兄弟の数） ###
# brother_num: 10

### 交叉メソッド ###
crossover:
  length: dependent_sum_blx
  impedance: n_point_crossover

### セグメントの特性インピーダンスの最小値 ###
minimum_impedance: 60

### セグメントの特性インピーダンスの最大値 ###
maximum_impedance: 160

### セグメントの特性インピーダンスの間隔 ###
impedance_step: 5

### セグメント長の最小値 ###
minimum_length: 1m

### セグメント長の間隔 ###
length_step: 0.5m

### 乱数シード ###
seeds:
- 3

### 最適化する観測点 ###
optpts:
- optpt1
- optpt2

### 観測点毎の重み ###
weight:
  optpt1: 1.0
  optpt2: 1.5  # 卒論には記述が無いですが，重み付けがされています．

### 観測波形に対応する理想波形の観測点 ###
versus:                 
  optpt1: vspt1
  optpt2: vspt2


### スコア計算関数 ###
score_calc_methods:
- - optpt1
  - integral
- - optpt2
  - integral
