---

###################################################
### アイパターン整形用のSTL基本形用設定ファイル ###
### 評価方法： アイマスク誤差面積               ###
###################################################

### STL設計に用いるテンプレートファイルのパス ###
template: ./template/basic/template_eye.sp

### 母集合の個体数 ###
# pop_size: 100

### 遺伝的アルゴリズムの繰り返し世代数 ###
# generation: 2000

### 一回の交叉で生成する子供の数（兄弟の数） ###
# brother_num: 8

### 乱数シード ###
seeds:
- 11

### セグメントの特性インピーダンスの最小値 ###
minimum_impedance: 40

### セグメントの特性インピーダンスの最大値 ###
maximum_impedance: 120

### セグメントの特性インピーダンスの間隔 ###
impedance_step: 5

### セグメント長の最小値 ###
minimum_length: 1m

### セグメント長の間隔 ###
length_step: 0.5m

### 最適化する観測点 ###
optpts:
- optpt3

### 観測点毎の重み ###
weight:
  optpt3: 1.0

### 観測波形に対応する理想波形の観測点 ###
versus:                 
  optpt3: vspt3

### アイパターン設計の設定ファイルのパス ###
eye_config_path: "./config/eyeconfigs/eye_config_basic.yml"


### スコア計算関数 ###
score_calc_methods:
- - optpt3
  - eye_diff_area
