---

#############################################
### OrCAD tlsim のSTL基本形用設定ファイル ###
#############################################

### STL設計に用いるテンプレートファイルのパス ###
template: ./template/basic/template_tlsim.spc

### 母集合の個体数 ###
# pop_size: 100

### 遺伝的アルゴリズムの繰り返し世代数 ###
# generation: 2000

### 一回の交叉で生成する子供の数（兄弟の数） ###
# brother_num: 8

### セグメントの特性インピーダンスの最小値 ###
minimum_impedance: 30

### セグメントの特性インピーダンスの最大値 ###
maximum_impedance: 120

### セグメントの特性インピーダンスの間隔 ###
impedance_step: 5

### 乱数シード ###
seeds:
- 1

### 回路シミュレータ名 ###
spice_name: tlsim

# spice_name が tlsim のとき、過渡解析を設定します。
# ※tlsim に対する開始時刻のコマンドオプションが不明なため，開始時刻指定は未実装です．
# [step, stop_time, start_time]
tlsim_tran:
- 10p
- 40n
- 20n

# テンプレートの観測点のうち，波形整形したい観測点を指定してください．
optpts:
- optpt1

### 観測点毎の重み ###
weight:
  optpt1: 1.0

### 観測波形に対応する理想波形の観測点 ###
versus:                 
  optpt1: vspt1

### スコア計算関数 ###
score_calc_methods:
- - optpt1
  - integral
