---

############################################
### WテンプレートSTL基本形用設定ファイル ###
############################################

### STL設計に用いるテンプレートファイルのパス ###
template: ./template/basic/template_W.sp

### 母集合の個体数 ###
pop_size: 100

### 遺伝的アルゴリズムの繰り返し世代数 ###
# generation: 2000

### 一回の交叉で生成する子供の数（兄弟の数） ###
# brother_num: 8

### 乱数シード ###
seeds:
- 1

# テンプレートの観測点のうち，波形整形したい観測点を指定してください．
optpts:
- optpt1

### 観測点毎の重み ###
weight:
  optpt1: 1.0

### 観測波形に対応する理想波形の観測点 ###
versus:                 
  optpt1: vspt1

### スコア計算関数 ###
score_calc_methods:
- - optpt1
  - integral
