---

##############################
### アイマスク設定ファイル ###
##############################

###### 注意事項 ######
# * この設定ファイルは"STL設定ファイル" や "アイ設定ファイル" ではなく，"アイマスク設定ファイル" です．
# * 実行時に引数で指定するような使い方ではなく，"アイ設定ファイル"の設定項目:eyemask_config_path でパスを指定して利用します．

# グラフ縦軸（電圧）の刻み幅
row_step: 0.01

# グラフ縦軸（電圧）の最小値
row_min: -1.0

# グラフ縦軸（電圧）の最大値
row_max: 2.0

# しきい値電圧[V]
threshold: 0.5

# 一周期のデータ数
period_num: 250

# 内側マスクの重み
inside_weight: 1.0

# 外側マスクの重み
outside_weight: 1.0

# 内側マスク上側の理想アイパターンとの隙間
inner_above_width: 5

# 内側マスク下側の理想アイパターンとの隙間
inner_below_width: 5

# 内側マスク両サイドの理想アイパターンとの隙間
inner_side_width : 5

# 外側マスク上側の理想アイパターンとの隙間
overshoot_allow_width: 5

# 外側マスク上側の理想アイパターンとの隙間
undershoot_allow_width: 5

# 内側マスクの傾き
grad: 0.5
